### ISSUE TITLE
Invalid or non-wallet transaction id

### ISSUE THREAD

**Issue by davidlandais** [216k155/lux#152]
Hello,

When i try to do `lux-cli gettransaction e346cc0626daaa64f0ecb266fa491bda81330a9136807ddcb2e33b154380168a`, i've got an error (`Invalid or non-wallet transaction id`) but using your explorer it seems to be ok (`https://explorer.luxcore.io/tx/e346cc0626daaa64f0ecb266fa491bda81330a9136807ddcb2e33b154380168a`). Am i wrong somewhere ?

I'm using lux under linux with your last release 5.1

**Comment by 216k155** [comment]
The RPC gettransaction call is intended to be used to receive transactional details in the wallet. If the transaction has not been sent from your wallet or received in your wallet, then you should use getrawtransaction, which can return any transaction in raw format as long as the transaction index is enabled. Otherwise, getrawtransaction will return the transaction only if it is still in the mempool or has an unspent output in the utxo for this transaction.

**Comment by davidlandais** [comment]
Thx for your fast response 👍
