### ISSUE TITLE
Windows Wallet Can't Find Connections To The Network

### ISSUE THREAD

**Issue by ledux6** [216k155/lux#70]
The 4.0v Lux Wallet doesn't find any connections to the Lux Network.

**Comment by rej156** [comment]
https://cdn.discordapp.com/attachments/379684706859483137/410306887574355988/lux.conf
Copy that into /%appdata%/lux/

It should help.

**Comment by 008** [comment]
Why devs cant put this lux.conf in lux-qt-wins.zip ??? Why ppl have too see that 0 connection problem and leave/sell LUX, thats bad for price!

**Comment by reset77** [comment]
Even with the fix it doesent find connections to the network, hope you can fix it

Thanks!

**Comment by cheekorobbins** [comment]
[debug.log](https://github.com/216k155/lux/files/1702648/debug.log)

Same problem, I've downloaded that config file but it's still not connecting.

**Comment by Leshiy174** [comment]
Good afternoon .
The wallet will not be synchronized 4.0.0
What to do?  Help me please.
In this state, several hours.
Screen in the attachment.
Thank you
![wallet lux](https://user-images.githubusercontent.com/36126018/35916326-e21d10a6-0c2b-11e8-9bb0-99467c81159d.jpg)

**Comment by iamisti** [comment]
same here, the new conf file didn't help

**Comment by slaczky** [comment]
+1, new config file did not help

**Comment by anorganix** [comment]
Hey guys, you need to be patient as a lot of people are moving to the new wallet and sync takes some time because seednodes are under a lot of stress/traffic. The conf option is an alternative to sync (from other nodes) without waiting for the seednodes to be available.

@cheekorobbins I'm glad you were patient and got your issue fixed.

@008 because you don't normally need conf and anyway it should be in the data directory, not in the wallet exe folder.
